name: Botu Calistir ve Siteyi Guncelle

on:
  schedule:
    - cron: '*/30 * * * *' # Her 30 dakikada bir çalışır
  workflow_dispatch: # Manuel tetikleme için

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Depoyu Çek (Checkout)
        uses: actions/checkout@v3

      - name: Python'u Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Kütüphaneleri Yükle
        run: |
          pip install requests beautifulsoup4

      - name: Botu Çalıştır
        run: python takip_botu.py

      - name: Değişiklikleri Kaydet ve Yayınla
        run: |
          git config --global user.name 'Takip Botu'
          git config --global user.email 'bot@noreply.github.com'
          git add .
          git commit -m "Otomatik güncelleme: $(date)" || exit 0
          git push
